name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: sudo apt-get install -qq libcfitsio-dev libreadline6-dev libncurses5-dev libfftw3-dev libgsl0-dev flex bison

    - name: get milk and cacao
      run: |
        git clone https://github.com/milk-org/milk.git
        cd milk
        ./fetch_coffee_dev.sh
        mkdir _build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/milk/_build
      run: cmake .. -DEXTRAMODULES="milk_module_example" -DINSTALLMAKEDEFAULT=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/milk/_build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Install
      working-directory: ${{github.workspace}}/milk/_build
      shell: bash
      run: sudo make install

    - name: Test
        working-directory: ${{github.workspace}}/milk/_build
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        #run: ctest -C $BUILD_TYPE
        run: |
          export MILK_ROOT=${HOME}/src/milk
          export MILK_INSTALLDIR=/usr/local/milk
          export PATH=${PATH}:${MILK_INSTALLDIR}/bin
          export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${MILK_INSTALLDIR}/lib/pkgconfig
          echo $PATH
          export TERM=xterm-256color
          ctest -C $BUILD_TYPE -D Experimental
